#!/bin/bash
set -e

if [ ! "$(which golangci-lint 2> /dev/null)" ]; then
    # curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
    GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
fi

golangci-lint run ./...
