version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Run tests
          command: dev/test
      - run:
          name: Run lint checks
          command: dev/lint
      - run:
          name: Run format checks
          command: dev/format-check
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
