apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: do-operator
  template:
    metadata:
      labels:
        name: do-operator
    spec:
      serviceAccountName: do-operator
      containers:
        - name: do-operator
          image: snormore/do-operator:latest
          command:
          - do-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "do-operator"
            - name: DIGITALOCEAN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: do-operator
                  key: DIGITALOCEAN_ACCESS_TOKEN
