name: release
on:
  push:
    tags:
      - v**
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Validate that the release manifest exists
        run: |
          [[ -f "releases/do-operator-$(git describe --tags).yaml" ]] || false
      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: Build and push docker image
        run: |
          make docker-build docker-push IMG_TAG="$(git describe --tags)"
