name: release
on:
  push:
    tags:
      - v**
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ^1.23
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate that the release manifest exists
        run: |
          [[ -f "releases/do-operator-$(git describe --tags).yaml" ]] || false
      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: Build and push docker image
        run: |
          make docker-build docker-push IMG_TAG="$(git describe --tags)"
